#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : vid.stab
Version  : 1.1.1
Release  : 1
URL      : https://github.com/georgmartius/vid.stab/archive/refs/tags/v1.1.1.tar.gz
Source0  : https://github.com/georgmartius/vid.stab/archive/refs/tags/v1.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: vid.stab-lib = %{version}-%{release}
Requires: vid.stab-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : pkg-config
BuildRequires : pkgconfig(orc-0.4)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
These files are now in the ffmpeg source tree (as of 25.04.2013). They will be removed here at some point.

%package dev
Summary: dev components for the vid.stab package.
Group: Development
Requires: vid.stab-lib = %{version}-%{release}
Provides: vid.stab-devel = %{version}-%{release}
Requires: vid.stab = %{version}-%{release}

%description dev
dev components for the vid.stab package.


%package lib
Summary: lib components for the vid.stab package.
Group: Libraries
Requires: vid.stab-license = %{version}-%{release}

%description lib
lib components for the vid.stab package.


%package license
Summary: license components for the vid.stab package.
Group: Default

%description license
license components for the vid.stab package.


%prep
%setup -q -n vid.stab-1.1.1
cd %{_builddir}/vid.stab-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693328169
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1693328169
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vid.stab
cp %{_builddir}/vid.stab-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/vid.stab/834f231e0b8ca5602e7c3bff10988f64b33f045f || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/vid.stab/boxblur.h
/usr/include/vid.stab/frameinfo.h
/usr/include/vid.stab/libvidstab.h
/usr/include/vid.stab/localmotion2transform.h
/usr/include/vid.stab/motiondetect.h
/usr/include/vid.stab/motiondetect_internal.h
/usr/include/vid.stab/motiondetect_opt.h
/usr/include/vid.stab/serialize.h
/usr/include/vid.stab/transform.h
/usr/include/vid.stab/transform_internal.h
/usr/include/vid.stab/transformfixedpoint.h
/usr/include/vid.stab/transformfloat.h
/usr/include/vid.stab/transformtype.h
/usr/include/vid.stab/transformtype_operations.h
/usr/include/vid.stab/vidstabdefines.h
/usr/include/vid.stab/vsvector.h
/usr/lib64/libvidstab.so
/usr/lib64/pkgconfig/vidstab.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvidstab.so.1.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vid.stab/834f231e0b8ca5602e7c3bff10988f64b33f045f
